version: '3.8'

services:
  bot:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - db
    networks:
      - vpn_bot_network

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: vpnbot
      POSTGRES_PASSWORD: vpnbotpass
      POSTGRES_DB: vpnbot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vpn_bot_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U vpnbot']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  vpn_bot_network:
    driver: bridge
