version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: vpnbot_db_local
    environment:
      POSTGRES_USER: vpnbot
      POSTGRES_PASSWORD: vpnbotpass
      POSTGRES_DB: vpnbot
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
